version: 0.2

phases:
  install:
    commands:
      - printenv
      - cd lambda/custom && npm install
  build:
    commands:
      - npm test
      - npm run build-aws-resource
artifacts:
  files:
    - lambda/custom/template.yaml
    - lamda/custom/AppSpec.yml
    - lambda/custom/BasicAlexaEchoHello.zip